d /etc/wyrelog 0750 root wyrelog -
d /etc/wyrelog/system 0750 root wyrelog -
d /etc/wyrelog/service 0750 root wyrelog -
d /var/lib/wyrelog 0750 wyrelog wyrelog -
d /var/lib/wyrelog/system 0750 wyrelog wyrelog -
d /var/lib/wyrelog/service 0750 wyrelog wyrelog -
d /var/lib/wyrelog/service/event-spool 0700 wyrelog wyrelog -
d /var/log/wyrelog 0750 wyrelog wyrelog -
d /var/log/wyrelog/system 0750 wyrelog wyrelog -
d /var/log/wyrelog/service 0750 wyrelog wyrelog -
d /run/wyrelog 0750 wyrelog wyrelog -
z /etc/wyrelog 0750 root wyrelog -
