/* SPDX-License-Identifier: GPL-3.0-or-later */
#pragma once

#include <glib.h>

#include "wyrelog/error.h"

G_BEGIN_DECLS;

typedef struct WylFactArtifactNamespace WylFactArtifactNamespace;

typedef struct
{
  const gchar *tenant_id;
  const gchar *graph_id;
  const gchar *store_uuid;
  guint64 format_version;
  guint64 path_encoding_version;
} WylFactStoreIdentity;

typedef enum
{
  WYL_FACT_STORE_IDENTITY_VALIDATE_ONLY = 0,
  WYL_FACT_STORE_IDENTITY_INITIALIZE_IF_EMPTY,
} WylFactStoreIdentityOpenMode;

typedef enum
{
  WYL_FACT_STORE_IDENTITY_RESULT_NONE = 0,
  WYL_FACT_STORE_IDENTITY_RESULT_IDENTITY,
  WYL_FACT_STORE_IDENTITY_RESULT_FORMAT,
  WYL_FACT_STORE_IDENTITY_RESULT_PATH_ENCODING,
  WYL_FACT_STORE_IDENTITY_RESULT_SCHEMA,
  WYL_FACT_STORE_IDENTITY_RESULT_OPEN,
  WYL_FACT_STORE_IDENTITY_RESULT_INTERNAL,
} WylFactStoreIdentityResult;

typedef enum
{
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_NONE = 0,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_CREATE,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_STORE_KIND,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_FORMAT_VERSION,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_STORE_UUID,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_PATH_ENCODING_VERSION,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_TENANT_ID,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_AFTER_GRAPH_ID,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_BEFORE_COMMIT,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_COMMIT,
  WYL_FACT_STORE_IDENTITY_TEST_FAULT_COMMIT_AND_ROLLBACK,
} WylFactStoreIdentityTestFault;

G_END_DECLS;
